apiVersion: v1
kind: ReplicationController
metadata:
   name: myjavaapp-rc
spec:
   replicas: 3
   selector: 
     app: myjavaapp
     version: 2.6.4
   template:
     metadata:
       labels:
          app: myjavaapp
          version: 2.6.4
     spec:
       containers:
       - name: myjavacontainer
         image: maha4iac/myonlinebooking:1
         ports:
          - containerPort: 8080